### ISSUE TITLE
not working in Vivaldi

### ISSUE THREAD

**Issue by dariopuerot** [owenschoppe/Citable#5]
Just installed Citable, and when trying to sign in, teh page:
https://accounts.google.com/signin/chrome/sync?ssp=1&continue=https%3A%2F%2Fwww.google.com%2F

gives an error 404

**Comment by owenschoppe** [comment]
Sorry, Vivaldi isn’t a supported browser. Give it a try in Chrome and see if it still doesn’t work.

**Comment by dariopuerot** [comment]
Ok, thank you very much.
